# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 3.2
  Exclude:
    - "vendor/**/*"
    - "infra/**/*"

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 120

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - "../spec/**/*.rb"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
